# Change these first
owner: legochancw # Your GitHub organization or username, where this repository lives
repo: upptime_som # The name of this repository

assignees:
  - legochancw

sites:
  - name: Production - EMAT Support
    url: https://support.mattex.com.hk
  - name: Development - EMAT Support
    url: https://dev-support.mattex.com.hk
  - name: SOM Web Portal
    url: https://som.mattex.com.hk
  - name: SOM - API (Auth)
    url: https://api.fours.app/auth
  - name: SOM - API (CIS-Project)
    url: https://api.fours.app/cis/projects
  - name: SOM - Konga
    url: https://konga.fours.app

status-website:
  cname: upptime.fours.app
  logoUrl: https://som.mattex.com.hk/_nuxt/img/fours_logo.a832252.png
  name: SOM Status Monitoring 
  introTitle: "**SOM Status Monitoring** is an uptime monitor and status page, powered entirely by GitHub."
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: EMAT - SOM 
      href: https://som.mattex.com.hk
    - title: Status
      href: /




      
#    - title: GitHub
#      href: https://github.com/$OWNER/$REPO

  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
